apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technitium-tsig-secret
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: technitium-tsig-secret
    creationPolicy: Owner
  data:
    - secretKey: tsig-secret
      remoteRef:
        key: prod/platform/technitium
        property: TECHNITIUM_TSIG_KEY
