apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authentik
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  repo: https://charts.goauthentik.io
  chart: authentik
  version: 2026.5.3
  targetNamespace: identity
  createNamespace: false
  valuesContent: |-
    global:
      env:
        - name: AUTHENTIK_POSTGRESQL__SSLMODE
          value: disable
      envFrom:
        - secretRef:
            name: authentik-secrets
    authentik:
      log_level: info
      error_reporting:
        enabled: false
      postgresql:
        host: platform-postgres-rw.database.svc.cluster.local
        name: authentik
        user: authentik
        port: "5432"
    postgresql:
      enabled: false
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-cloudflare
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - authentik.infra.plexplease.com
        tls:
          - secretName: authentik-tls
            hosts:
              - authentik.infra.plexplease.com
