apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: identity
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: prod/platform/authentik
        property: AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_BOOTSTRAP_EMAIL
      remoteRef:
        key: prod/platform/authentik
        property: AUTHENTIK_BOOTSTRAP_EMAIL
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD_HASH
      remoteRef:
        key: prod/platform/authentik
        property: AUTHENTIK_BOOTSTRAP_PASSWORD_HASH
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      remoteRef:
        key: prod/platform/authentik
        property: AUTHENTIK_BOOTSTRAP_TOKEN
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: prod/platform/authentik
        property: AUTHENTIK_POSTGRESQL_PASSWORD
