---
vcenter:
  datacenter: "HOMELAB"
  cluster: "Primary"
  host: "10.10.10.11"
  datastore: "iSCSI_PRODUCTION"
  network: "VM Network"

content_library:
  name: "GOLDEN"
  template: "ubuntu-24.04-lts-golden"

vm_specs:
  cpu: 4
  memory: 8192
  disk: 50

deployment:
  tags:
    - "ubuntu"
    - "ubuntu-2404"
    - "benchmark"
  vm_name_prefix: "iscsi-bench"
  vm_name_domain: "mgmt.plexplease.com"

network:
  ipv4_address: "10.10.10.102"
  ipv4_netmask: 24
  ipv4_gateway: "10.10.10.1"
  dns_servers:
    - "8.8.8.8"
    - "8.8.4.4"
