vcenter:
  datacenter: HOMELAB
  cluster: Primary
  host: esxi-01.mgmt.plexplease.com
  datastore: NVME_2TB_970_SAMSUNG_EVO_M.2
  network: VM Network
content_library:
  name: GOLDEN
  template: photon-5.0-golden
vm_specs:
  cpu: 8
  ram_gb: 8
  guest_id: vmwarePhoton64Guest
  disk_size_gb: 50
deployment:
  tags:
  - photon
  - dns
  vm_name_prefix: photon
  vm_name_domain: mgmt.plexplease.com
logging:
  files:
  - path: /var/log/technitium/dns/*.log
    owner: dns-server
    group: dns-server
    mode: "0640"
    rotate_count: 14
    max_size: 100M
  journald:
    vacuum_enabled: true
    vacuum_time: 14d
    vacuum_size: 512M
