vcenter:
  datacenter: HOMELAB
  cluster: Primary
  host: esxi-01.mgmt.plexplease.com
  datastore: ds-nfs-prod
  network: VM Network
content_library:
  name: GOLDEN
  template: ubuntu-24.04-lts-golden
vm_specs:
  cpu: 40
  memory: 40960
  disk: 400
deployment:
  tags:
  - ubuntu
  - ubuntu-2404
  - combined_dev
  vm_name_prefix: combined-dev
  vm_name_domain: mgmt.plexplease.com
