vcenter:
  datacenter: HOMELAB
  cluster: Primary
  host: 10.10.10.11
  datastore: NVME_2TB_970_SAMSUNG_EVO_M.2
  network: VM Network
content_library:
  name: GOLDEN
  template: ubuntu-26.04-golden
vm_specs:
  cpu: 4
  memory: 8192
  disk: 50
deployment:
  tags:
  - ubuntu
  vm_name_prefix: ubuntu
  vm_name_domain: mgmt.plexplease.com
