---
alloy_version: "latest"
alloy_user: "alloy"
alloy_group: "alloy"
alloy_home: "/etc/alloy"
alloy_config_dir: "/etc/alloy"
alloy_config_file: "/etc/alloy/config.river"
alloy_log_level: "info"

alloy_central_prometheus_url: "http://10.10.10.30:9090"
alloy_central_loki_url: "http://10.10.10.30:3100"

alloy_scrape_interval: "15s"
alloy_evaluation_interval: "15s"

alloy_enable_docker_metrics: "{{ 'tag_docker' in group_names }}"
alloy_docker_socket_path: "/var/run/docker.sock"

alloy_extra_scrape_targets: []
alloy_extra_log_paths: []

alloy_skip: false
