apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: 87.2.1
  targetNamespace: observability
  createNamespace: false
  valuesContent: |-
    fullnameOverride: kube-prometheus-stack

    grafana:
      enabled: true
      defaultDashboardsTimezone: browser
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.observability.svc.cluster.local
      service:
        type: ClusterIP
        port: 80
      ingress:
        enabled: false

    alertmanager:
      enabled: true
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by:
            - namespace
            - alertname
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
          receiver: apprise
          routes:
            - matchers:
                - alertname = "Watchdog"
              receiver: apprise
              repeat_interval: 12h
        receivers:
          - name: apprise
            webhook_configs:
              - send_resolved: true
                url: http://apprise-alertmanager-webhook.notifications.svc.cluster.local:3000

    prometheus:
      prometheusSpec:
        retention: 14d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: storage-standard
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi

    kubeEtcd:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
