apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  repo: https://grafana-community.github.io/helm-charts
  chart: loki
  version: 18.1.1
  targetNamespace: observability
  createNamespace: false
  valuesContent: |-
    deploymentMode: Monolithic

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      limits_config:
        retention_period: 7d
      compactor:
        retention_enabled: true
        working_directory: /var/loki/compactor
        delete_request_store: filesystem

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: storage-standard
        size: 20Gi

    gateway:
      enabled: true

    minio:
      enabled: false

    test:
      enabled: false

    lokiCanary:
      enabled: false
