apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-object-store
  namespace: backup
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: velero-object-store
    creationPolicy: Owner
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .awsAccessKeyId }}
          aws_secret_access_key={{ .awsSecretAccessKey }}
  data:
    - secretKey: awsAccessKeyId
      remoteRef:
        key: prod/platform/velero
        property: AWS_ACCESS_KEY_ID
    - secretKey: awsSecretAccessKey
      remoteRef:
        key: prod/platform/velero
        property: AWS_SECRET_ACCESS_KEY
