apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: platform-namespace-daily
  namespace: backup
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  schedule: "17 3 * * *"
  template:
    ttl: 168h0m0s
    storageLocation: truenas-s3
    includedNamespaces:
      - platform
    snapshotVolumes: false
    defaultVolumesToFsBackup: true
