apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config/namespaces.yaml
  - ../../platform/openbao/overlays/k3s-01
  - ../../platform/argocd/overlays/k3s-01
  - ../../platform/cert-manager/overlays/k3s-01
  - ../../platform/external-secrets/overlays/k3s-01
  - ../../platform/external-dns/overlays/k3s-01
  - ../../platform/democratic-csi/overlays/k3s-01
  - ../../platform/storage/overlays/k3s-01
