apiVersion: v1
kind: Service
metadata:
  name: apprise-alertmanager-webhook
  namespace: notifications
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: apprise-alertmanager-webhook
  ports:
    - name: http
      port: 3000
      targetPort: http
