apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apprise-config
  namespace: notifications
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: apprise-config
    creationPolicy: Owner
    template:
      data:
        apprise.yml: |
          {{ .appriseConfig }}
  data:
    - secretKey: appriseConfig
      remoteRef:
        key: prod/platform/notifications
        property: APPRISE_CONFIG
