apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apprise-config-secret.yaml
  - apprise-deployment.yaml
  - apprise-service.yaml
  - alertmanager-webhook-config.yaml
  - alertmanager-webhook-deployment.yaml
  - alertmanager-webhook-service.yaml
  - ingress.yaml
