apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  version: 9.7.0
  targetNamespace: argocd
  createNamespace: true
