apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-postgres-authentik
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: platform-postgres-authentik
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: authentik
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: prod/platform/authentik
        property: AUTHENTIK_POSTGRESQL_PASSWORD
