apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: platform-postgres-nightly
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: platform-postgres
  method: barmanObjectStore
