apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      server: http://10.10.10.30:8201
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-k3s-01
          role: k3s-01-external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
