apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - local-zfs-helmchart.yaml
  - nfs-helmchart.yaml
  - iscsi-helmchart.yaml
  - truenas-iscsi-config-secret.yaml
  - truenas-nfs-config-secret.yaml
