apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-truenas-nfs-config
  namespace: democratic-csi
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: democratic-csi-truenas-nfs-config
    creationPolicy: Owner
    template:
      data:
        driver-config-json: |
          {
            "driver": "freenas-api-nfs",
            "httpConnection": {
              "protocol": "http",
              "host": "10.10.10.20",
              "port": 80,
              "apiVersion": 2,
              "apiKey": "{{ .truenasApiKey }}"
            },
            "zfs": {
              "datasetParentName": "K3S_HDD/k3s-nfs",
              "detachedSnapshotsDatasetParentName": "K3S_HDD/k3s-nfs-snapshots",
              "datasetEnableQuotas": true,
              "datasetEnableReservation": false
            },
            "nfs": {
              "shareHost": "10.10.10.20",
              "shareAlldirs": false,
              "shareMaprootUser": "root",
              "shareMaprootGroup": "root"
            }
          }
  data:
    - secretKey: truenasApiKey
      remoteRef:
        key: prod/platform/truenas
        property: TRUENAS_API_KEY
