apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-truenas-iscsi-config
  namespace: democratic-csi
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: democratic-csi-truenas-iscsi-config
    creationPolicy: Owner
    template:
      data:
        driver-config-json: |
          {
            "driver": "freenas-api-iscsi",
            "httpConnection": {
              "protocol": "http",
              "host": "10.10.10.20",
              "port": 80,
              "apiVersion": 2,
              "apiKey": "{{ .truenasApiKey }}"
            },
            "zfs": {
              "datasetParentName": "K3S_HDD/k3s-iscsi",
              "detachedSnapshotsDatasetParentName": "K3S_HDD/k3s-iscsi-snapshots"
            },
            "iscsi": {
              "targetPortal": "10.10.10.20:3260",
              "interface": "",
              "namePrefix": "k3s-",
              "nameSuffix": "",
              "targetGroups": [
                {
                  "targetGroupPortalGroup": 1,
                  "targetGroupInitiatorGroup": 1,
                  "targetGroupAuthType": "None"
                }
              ],
              "extentInsecureTpc": true,
              "extentXenCompat": false,
              "extentDisablePhysicalBlocksize": true,
              "extentBlocksize": 512,
              "extentRpm": "SSD",
              "extentAvailThreshold": 0
            }
          }
  data:
    - secretKey: truenasApiKey
      remoteRef:
        key: prod/platform/truenas
        property: TRUENAS_API_KEY
