# name        lanes                   alias                    index     speed   autoneg
Ethernet0       1     oneGigE1/1           1     1000     1
Ethernet1       2     oneGigE1/2           2     1000     1
Ethernet2       3     oneGigE1/3           3     1000     1
Ethernet3       4     oneGigE1/4           4     1000     1
Ethernet4       5     oneGigE1/5           5     1000     1
Ethernet5       6     oneGigE1/6           6     1000     1
Ethernet6       7     oneGigE1/7           7     1000     1
Ethernet7       8     oneGigE1/8           8     1000     1
Ethernet8       9     oneGigE1/9           9     1000     1
Ethernet9       10    oneGigE1/10          10    1000     1
Ethernet10      11    oneGigE1/11          11    1000     1
Ethernet11      12    oneGigE1/12          12    1000     1
Ethernet12      13    oneGigE1/13          13    1000     1
Ethernet13      14    oneGigE1/14          14    1000     1
Ethernet14      15    oneGigE1/15          15    1000     1
Ethernet15      16    oneGigE1/16          16    1000     1
Ethernet16      17    oneGigE1/17          17    1000     1
Ethernet17      18    oneGigE1/18          18    1000     1
Ethernet18      19    oneGigE1/19          19    1000     1
Ethernet19      20    oneGigE1/20          20    1000     1
Ethernet20      21    oneGigE1/21          21    1000     1
Ethernet21      22    oneGigE1/22          22    1000     1
Ethernet22      23    oneGigE1/23          23    1000     1
Ethernet23      24    oneGigE1/24          24    1000     1
Ethernet48      64    tenGigE1/49          49    10000    0
Ethernet49      63    tenGigE1/50          50    10000    0
Ethernet50      62    tenGigE1/51          51    10000    0
Ethernet51      61    tenGigE1/52          52    10000    0
Ethernet52      69,70,71,72           hundredGigE1/53     53      100000           0
Ethernet56      73,74,75,76           hundredGigE1/54     54      100000           0
