#!/usr/bin/env python3
"""Aggregate CI runner requirements from per-repo manifests into Ansible-generated files.

Each repo may ship: requirements/ci-runner.manifest.yaml

Run from homelab-gitops root:
  python3 scripts/sync_ci_runner_requirements.py
  make sync-ci-runners
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    raise SystemExit(1)

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "config" / "ci-runner-repos.yaml"
OUT_DIR = ROOT / "ansible" / "generated" / "ci_runner"
MANIFEST_NAME = "requirements/ci-runner.manifest.yaml"


@dataclass
class RepoManifest:
    name: str
    path: Path
    schema_version: int = 1
    python_version: str = "3.12"
    apt_packages: list[str] = field(default_factory=list)
    pip_files: list[Path] = field(default_factory=list)


def expand_path(raw: str) -> Path:
    return Path(raw).expanduser().resolve()


def load_registry() -> list[dict]:
    data = yaml.safe_load(REGISTRY.read_text()) or {}
    repos: list[dict] = data.get("repos") or []
    out: list[dict] = []
    for entry in repos:
        if not entry.get("enabled", True):
            continue
        out.append(entry)
    return out


def load_registry_from(registry_path: Path) -> list:
    data = yaml.safe_load(registry_path.read_text()) or {}
    repos = data.get("repos") or []
    out = []
    for entry in repos:
        if not entry.get("enabled", True):
            continue
        out.append(entry)
    return out


def load_manifest(repo_name: str, repo_root: Path) -> RepoManifest | None:
    manifest_path = repo_root / MANIFEST_NAME
    if not manifest_path.is_file():
        return None
    raw = yaml.safe_load(manifest_path.read_text()) or {}
    apt: list[str] = list(raw.get("apt_packages") or [])
    system_file = raw.get("system_packages_file")
    if system_file:
        sf = repo_root / system_file
        if sf.is_file():
            apt.extend(
                line.strip()
                for line in sf.read_text().splitlines()
                if line.strip() and not line.strip().startswith("#")
            )

    pip_files: list[Path] = []
    seen_pip: set[Path] = set()
    for item in raw.get("pip_requirements_files") or []:
        p = (repo_root / item).resolve()
        if p not in seen_pip:
            pip_files.append(p)
            seen_pip.add(p)
    venv_file = (raw.get("python") or {}).get("venv_packages")
    if venv_file:
        p = (repo_root / venv_file).resolve()
        if p not in seen_pip:
            pip_files.append(p)
            seen_pip.add(p)

    py = raw.get("python") or {}
    return RepoManifest(
        name=repo_name,
        path=repo_root,
        schema_version=int(raw.get("schema_version", 1)),
        python_version=str(py.get("version", raw.get("python_version", "3.12"))),
        apt_packages=sorted(set(apt)),
        pip_files=pip_files,
    )


def merge_manifests(manifests: list[RepoManifest]) -> tuple[list[str], str, str]:
    apt_union: set[str] = set()
    python_versions: list[str] = []
    pip_sections: list[str] = []

    for m in manifests:
        apt_union.update(m.apt_packages)
        python_versions.append(m.python_version)
        pip_sections.append(f"# --- {m.name} ({m.path}) ---")
        for pip_file in m.pip_files:
            if not pip_file.is_file():
                pip_sections.append(f"# MISSING: {pip_file}")
                continue
            pip_sections.append(pip_file.read_text().rstrip() + "\n")

    # Prefer lowest pinned minor that satisfies all repos (conservative for CI).
    python_version = sorted(python_versions)[0] if python_versions else "3.12"
    pip_blob = "\n".join(pip_sections).strip() + "\n"
    return sorted(apt_union), pip_blob, python_version


def write_outputs(
    apt: list[str],
    pip_blob: str,
    python_version: str,
    manifests: list[RepoManifest],
    out_dir: Path,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "apt-packages.txt").write_text("\n".join(apt) + ("\n" if apt else ""))

    header = [
        "# AUTO-GENERATED by scripts/sync_ci_runner_requirements.py — do not edit",
        f"# Sources: {', '.join(m.name for m in manifests) or '(none)'}",
        "",
    ]
    (out_dir / "pip-requirements.txt").write_text("\n".join(header) + pip_blob)

    meta = {
        "generated_by": "scripts/sync_ci_runner_requirements.py",
        "repos": [{"name": m.name, "path": str(m.path)} for m in manifests],
        "ci_runner_python_version": python_version,
        "ci_runner_apt_packages": apt,
        "ci_runner_pip_requirements_path": str(out_dir / "pip-requirements.txt"),
        "ci_runner_cache_root": "/var/cache/ai-gateway",
        "ci_runner_venv_seed_path": "/var/cache/ai-gateway/venv-ci-seed",
    }
    (out_dir / "vars.yaml").write_text(yaml.safe_dump(meta, sort_keys=False))

    print(f"Wrote {out_dir}/apt-packages.txt ({len(apt)} packages)")
    print(f"Wrote {out_dir}/pip-requirements.txt")
    print(f"Wrote {out_dir}/vars.yaml (python {python_version}, {len(manifests)} repos)")


def main() -> int:
    parser = argparse.ArgumentParser(description="Aggregate CI runner manifests from registered repos")
    parser.add_argument("--registry", type=Path, default=REGISTRY)
    parser.add_argument("--out", type=Path, default=OUT_DIR)
    args = parser.parse_args()

    registry = args.registry
    out_dir = args.out

    manifests: list[RepoManifest] = []
    missing: list[str] = []

    for entry in load_registry_from(registry):
        name = entry["name"]
        root = expand_path(entry["path"])
        if not root.is_dir():
            missing.append(f"{name}: path not found: {root}")
            continue
        m = load_manifest(name, root)
        if m is None:
            missing.append(f"{name}: no {MANIFEST_NAME}")
            continue
        manifests.append(m)
        print(f"  + {name} ({root})")

    if missing:
        for line in missing:
            print(f"  skip: {line}")

    apt, pip_blob, py_ver = merge_manifests(manifests)
    write_outputs(apt, pip_blob, py_ver, manifests, out_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
