---
- name: Install Docker (Photon OS)
  ansible.builtin.command: tdnf install -y docker
  register: docker_install_photon
  changed_when: "'Nothing to do' not in docker_install_photon.stdout"
  when: ansible_facts['distribution'] == 'VMware Photon OS'

- name: Install Docker (Ubuntu)
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-v2
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install Docker Compose (Photon OS)
  ansible.builtin.command: tdnf install -y docker-compose
  register: compose_install_photon
  changed_when: "'Nothing to do' not in compose_install_photon.stdout"
  when: ansible_facts['distribution'] == 'VMware Photon OS'

- name: Create systemd override directory for Docker
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: ansible_facts['os_family'] == 'Debian'

- name: Override Docker systemd service ExecStart to allow hosts in daemon.json
  ansible.builtin.copy:
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  register: docker_systemd_override
  when: ansible_facts['os_family'] == 'Debian'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  when: docker_systemd_override.changed | default(false)

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
