- name: Discover and Group Hosts
  hosts: all
  gather_facts: true
  serial: 0
- name: Configure Ubuntu Hosts
  hosts: tag_ubuntu
  become: true
  roles:
  - base
  - security
- name: Configure Photon OS Hosts
  hosts: tag_photon
  become: true
  tasks:
  - name: Ensure all packages are up to date (Photon)
    ansible.builtin.command: tdnf update -y
    register: tdnf_update
    changed_when: '''Nothing to do'' not in tdnf_update.stdout'
  - name: Ensure SSH hardening (Photon)
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '{{ item.regexp }}'
      line: '{{ item.line }}'
      state: present
    loop:
    - regexp: ^PermitRootLogin
      line: PermitRootLogin no
    - regexp: ^PasswordAuthentication
      line: PasswordAuthentication no
    notify: Restart sshd (Photon)
  handlers:
  - name: Restart sshd (Photon)
    ansible.builtin.systemd:
      name: sshd
      state: restarted
- name: Configure Docker nodes
  hosts: tag_docker
  become: true
  roles:
  - docker
- name: primary_dns
  hosts: tag_dns
  become: true
  roles:
  - dns_technitium
  - security
  - base
